version: '3.9'

volumes:
  postgres_data:
    driver: local

networks:
  web:
    external: true

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=accesshub"
      - "POSTGRES_USER=accesshub"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "5433:8080"
